spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev?useTimezone=true&serverTimezone=UTC
    username: sfg_dev_user
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      dd-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: true
#    properties:#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: guru_database_create.sql